%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.5 and Fixed-Point Designer 6.2           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function C = MatrixC_wrapper_fixpt(c00,c11,c22,c33,c01,c23)
    fm = get_fimath();
    c00_in = fi( c00, 0, 16, 18, fm );
    c11_in = fi( c11, 0, 16, 0, fm );
    c22_in = fi( c22, 0, 16, 19, fm );
    c33_in = fi( c33, 0, 16, 4, fm );
    c01_in = fi( c01, 0, 16, 11, fm );
    c23_in = fi( c23, 1, 16, 12, fm );
    [C_out] = MatrixC_fixpt( c00_in, c11_in, c22_in, c33_in, c01_in, c23_in );
    C = double( C_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
