//
// Prerelease License - for engineering feedback and testing purposes
// only. Not for sale.
// File: calcDeltaChi2_fixpt.cpp
//
// MATLAB Coder version            : 4.1
// C/C++ source code generated on  : 28-Jun-2018 15:10:10
//

// Include Files
#include "calcDeltaChi2_fixpt.h"

// Function Definitions

//
// Arguments    : const short res[2]
//                const unsigned short RmatInv[4]
// Return Type  : unsigned short
//
unsigned short calcDeltaChi2_fixpt(const short res[2], const unsigned short
  RmatInv[4])
{
  long i0;
  long i1;
  long i2;
  long i3;
  long i4;
  long i5;
  long i6;
  long i7;

  // %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
  //                                                                           % 
  //            Generated by MATLAB 9.5 and Fixed-Point Designer 6.2           % 
  //                                                                           % 
  // %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
  i0 = (long)(res[0] * res[0]) * RmatInv[0];
  if ((i0 & 140737488355328L) != 0L) {
    i0 |= -140737488355328L;
  } else {
    i0 &= 140737488355327L;
  }

  i1 = (long)(res[1] * res[1]) * RmatInv[3];
  if ((i1 & 140737488355328L) != 0L) {
    i1 |= -140737488355328L;
  } else {
    i1 &= 140737488355327L;
  }

  if ((i0 & 281474976710656L) != 0L) {
    i2 = i0 | -281474976710656L;
  } else {
    i2 = i0 & 281474976710655L;
  }

  if ((i1 & 281474976710656L) != 0L) {
    i3 = i1 | -281474976710656L;
  } else {
    i3 = i1 & 281474976710655L;
  }

  i0 = i2 + i3;
  if ((i0 & 281474976710656L) != 0L) {
    i0 |= -281474976710656L;
  } else {
    i0 &= 281474976710655L;
  }

  i1 = (long)(res[0] * res[1]) << 1;
  if ((i1 & 8589934592L) != 0L) {
    i4 = i1 | -8589934592L;
  } else {
    i4 = i1 & 8589934591L;
  }

  i1 = i4 * RmatInv[2];
  if ((i1 & 562949953421312L) != 0L) {
    i1 |= -562949953421312L;
  } else {
    i1 &= 562949953421311L;
  }

  if ((i0 & 1125899906842624L) != 0L) {
    i5 = i0 | -1125899906842624L;
  } else {
    i5 = i0 & 1125899906842623L;
  }

  if ((i1 & 1125899906842624L) != 0L) {
    i6 = i1 | -1125899906842624L;
  } else {
    i6 = i1 & 1125899906842623L;
  }

  i0 = i5 + i6;
  if ((i0 & 1125899906842624L) != 0L) {
    i7 = i0 | -1125899906842624L;
  } else {
    i7 = i0 & 1125899906842623L;
  }

  return (unsigned short)(i7 >> 26);
}

//
// File trailer for calcDeltaChi2_fixpt.cpp
//
// [EOF]
//
