%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.5 and Fixed-Point Designer 6.2           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function x = VectorX_wrapper_fixpt(inv2R,phi0,tanL,z0)
    fm = get_fimath();
    inv2R_in = fi( inv2R, 0, 16, 13, fm );
    phi0_in = fi( phi0, 0, 16, 4, fm );
    tanL_in = fi( tanL, 1, 16, 13, fm );
    z0_in = fi( z0, 1, 16, 8, fm );
    [x_out] = VectorX_fixpt( inv2R_in, phi0_in, tanL_in, z0_in );
    x = double( x_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
