//
// Prerelease License - for engineering feedback and testing purposes
// only. Not for sale.
// File: VectorX_fixpt.cpp
//
// MATLAB Coder version            : 4.1
// C/C++ source code generated on  : 10-Aug-2018 16:33:54
//

// Include Files
#include "VectorX_fixpt.h"

// Function Definitions

//
// Arguments    : unsigned short inv2R
//                unsigned short phi0
//                short tanL
//                short z0
//                short x[4]
// Return Type  : void
//
void VectorX_fixpt(unsigned short inv2R, unsigned short phi0, short tanL, short
                   z0, short x[4])
{
  // %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
  //                                                                           % 
  //            Generated by MATLAB 9.5 and Fixed-Point Designer 6.2           % 
  //                                                                           % 
  // %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
  x[0] = (short)((unsigned int)inv2R >> 10);
  x[1] = (short)((unsigned int)phi0 >> 1);
  x[2] = (short)(tanL >> 10);
  x[3] = (short)(z0 >> 5);
}

//
// File trailer for VectorX_fixpt.cpp
//
// [EOF]
//
