%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.5 and Fixed-Point Designer 6.2           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function C_new = MatrixC_1_wrapper_fixpt(C,K,S)
    fm = get_fimath();
    C_in = fi( C, 1, 16, -1, fm );
    K_in = fi( K, 1, 16, 14, fm );
    S_in = fi( S, 1, 16, -1, fm );
    [C_new_out] = MatrixC_1_fixpt( C_in, K_in, S_in );
    C_new = double( C_new_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
