%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.5 and Fixed-Point Designer 6.2           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function x_new = VectorX_1_wrapper_fixpt(x,K,res)
    fm = get_fimath();
    x_in = fi( x, 1, 16, 3, fm );
    K_in = fi( K, 1, 16, 14, fm );
    res_in = fi( res, 1, 16, 9, fm );
    [x_new_out] = VectorX_1_fixpt( x_in, K_in, res_in );
    x_new = double( x_new_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
