%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.5 and Fixed-Point Designer 6.2           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function K = MatrixK_fixpt(St, RmatInv)
    fm = get_fimath();

    K = fi(zeros(8,1), 1, 16, 14, fm);
    for i0=1:4
        for i1=1:2
            K(fi(i0, 0, 3, 0, fm) + bitshift(i1-1, 2)) = 0;
            for i2=1:2
                K(fi(i0, 0, 3, 0, fm) + bitshift(i1-1, 2)) = K(fi(i0, 0, 3, 0, fm) + bitshift(i1-1, 2)) + ...
                    St(fi(i0, 0, 3, 0, fm) + bitshift(i2-1, 2)) * RmatInv(fi(i2, 0, 2, 0, fm) + bitshift(i1-1, 1));
            end
        end
    end
end


function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
