%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.5 and Fixed-Point Designer 6.2           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function [ res ] = VectorRes_fixpt(m, H, x)
    fm = get_fimath();

    res = fi(zeros(2,1), 1, 16, 9, fm);
    for i0=1:2
        d0 = fi(0, 1, 16, 3, fm);
        for i1=1:4
            d0(:) = d0 + H(fi(i0, 0, 2, 0, fm) + bitshift(i1-1, 1)) * x(i1);
        end
        res(i0) = m(i0) - d0;
    end
end


function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
