%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.5 and Fixed-Point Designer 6.2           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function [ dChi2 ] = calcDeltaChi2_fixpt(res, RmatInv)
    
    fm = get_fimath();

    dChi2 = fi((res(1,1) * res(1,1) * RmatInv(1,1) + res(2,1) * res(2,1) * ...
        RmatInv(4,1)) + fi(2.0, 0, 2, 0, fm) * (res(1,1) * res(2,1)) * RmatInv(3,1), 0, 16, 17, fm);
end


function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
