%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.5 and Fixed-Point Designer 6.2           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function dChi2 = calcDeltaChi2_wrapper_fixpt(res,RmatInv)
    fm = get_fimath();
    res_in = fi( res, 1, 16, 9, fm );
    RmatInv_in = fi( RmatInv, 0, 16, 25, fm );
    [dChi2_out] = calcDeltaChi2_fixpt( res_in, RmatInv_in );
    dChi2 = double( dChi2_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
