//
// Prerelease License - for engineering feedback and testing purposes
// only. Not for sale.
// File: MatrixC_fixpt.cpp
//
// MATLAB Coder version            : 4.1
// C/C++ source code generated on  : 28-Jun-2018 14:18:00
//

// Include Files
#include "MatrixC_fixpt.h"

// Function Definitions

//
// Arguments    : unsigned short c00
//                unsigned short c11
//                unsigned short c22
//                unsigned short c33
//                unsigned short c01
//                short c23
//                short C[16]
// Return Type  : void
//
void MatrixC_fixpt(unsigned short, unsigned short c11, unsigned short, unsigned
                   short c33, unsigned short c01, short c23, short C[16])
{
  // %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
  //                                                                           % 
  //            Generated by MATLAB 9.5 and Fixed-Point Designer 6.2           % 
  //                                                                           % 
  // %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
  C[0] = 0;
  C[5] = (short)((unsigned int)c11 >> 1);
  C[10] = 0;
  C[15] = (short)((unsigned int)c33 >> 5);
  C[4] = (short)((unsigned int)c01 >> 12);
  C[14] = (short)(c23 >> 13);
  C[8] = 0;
  C[12] = 0;
  C[9] = 0;
  C[13] = 0;
  C[1] = C[4];
  C[11] = C[14];
  C[2] = 0;
  C[3] = 0;
  C[6] = 0;
  C[7] = 0;
}

//
// File trailer for MatrixC_fixpt.cpp
//
// [EOF]
//
