%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.5 and Fixed-Point Designer 6.2           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function V = MatrixV_wrapper_fixpt(r,z,inv2R,tanL)
    fm = get_fimath();
    r_in = fi( r, 0, 10, 0, fm );
    z_in = fi( z, 1, 13, 0, fm );
    inv2R_in = fi( inv2R, 0, 16, 13, fm );
    tanL_in = fi( tanL, 1, 16, 13, fm );
    [V_out] = MatrixV_fixpt( r_in, z_in, inv2R_in, tanL_in );
    V = double( V_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
