%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.5 and Fixed-Point Designer 6.2           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function [ C ] = MatrixC_fixpt(c00, c11, c22, c33, c01, c23)
    fm = get_fimath();

    C = fi(zeros(16,1), 1, 16, -1, fm);
    C(1,1)  = c00;
    C(6,1)  = c11;
    C(11,1) = c22;
    C(16,1) = c33;
    C(5,1)  = c01;
    C(15,1) = c23;
    C(9,1)  = 0.0;
    C(13,1) = 0.0;
    C(10,1) = 0.0;
    C(14,1) = 0.0;
    C(2,1)  = C(5,1);
    C(12,1) = C(15,1);
    C(3,1)  = C(9,1);
    C(4,1) = C(13,1);
    C(7,1)  = C(10,1);
    C(8,1)  = C(14,1);
end


function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
