%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.5 and Fixed-Point Designer 6.2           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function [ C_new ] = MatrixC_1_fixpt(C, K, S)
    fm = get_fimath();

    C_new = fi(zeros(16,1), 1, 16, 2, fm);
    for i0 =1:4
        for i1=1:4
            d0 = fi(0, 1, 16, -1, fm);
            for i2=1:2
                d0(:) = d0 + K(fi(i0, 0, 3, 0, fm) + bitshift(i2-1, 2)) * S(fi(i2, 0, 2, 0, fm) + bitshift(i1-1, 1));
            end
            C_new(fi(i0, 0, 3, 0, fm) + bitshift(i1-1, 2)) = C(fi(i0, 0, 3, 0, fm) + bitshift(i1-1, 2)) - d0;
        end
    end
end


function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
