%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.5 and Fixed-Point Designer 6.2           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function [ St ] = MatrixS_transpose_fixpt(S)
    fm = get_fimath();

    St = fi(zeros(8,1), 1, 16, -1, fm);
    for i0=1:2
        for i1=1:4
            St(fi(i1, 0, 3, 0, fm) + bitshift(i0-1, 2)) = S(fi(i0, 0, 2, 0, fm) + bitshift(i1-1, 1));
        end
    end
    
end


function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
