//
// Prerelease License - for engineering feedback and testing purposes
// only. Not for sale.
// File: MatrixH_fixpt.cpp
//
// MATLAB Coder version            : 4.1
// C/C++ source code generated on  : 10-Aug-2018 16:50:34
//

// Include Files
#include "MatrixH_fixpt.h"

// Function Definitions

//
// Arguments    : unsigned short r
//                short H[8]
// Return Type  : void
//
void MatrixH_fixpt(unsigned short r, short H[8])
{
  short i0;

  // %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
  //                                                                           % 
  //            Generated by MATLAB 9.5 and Fixed-Point Designer 6.2           % 
  //                                                                           % 
  // %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
  i0 = (short)r;
  if ((i0 & 1024) != 0) {
    i0 = (short)-(i0 | -1024);
  } else {
    i0 = (short)-(i0 & 1023);
  }

  if ((i0 & 1024) != 0) {
    H[0] = (short)(i0 | -1024);
  } else {
    H[0] = (short)(i0 & 1023);
  }

  H[2] = 1;
  H[4] = 0;
  H[6] = 0;
  H[1] = 0;
  H[3] = 0;
  i0 = (short)r;
  if ((i0 & 1024) != 0) {
    H[5] = (short)(i0 | -1024);
  } else {
    H[5] = (short)(i0 & 1023);
  }

  H[7] = 1;
}

//
// File trailer for MatrixH_fixpt.cpp
//
// [EOF]
//
